-- ----------------------------
-- Drop [CAMPUS].[BANNERVIEWSTAT] table
-- ----------------------------    
IF EXISTS (
    SELECT * FROM sysobjects WHERE id = object_id(N'[CAMPUS].[BANNERVIEWSTAT]') AND OBJECTPROPERTY(id, N'IsTable') = 1
)
BEGIN
    DROP TABLE [CAMPUS].[BANNERVIEWSTAT]
END
GO

----------------------------------
-- Create [CAMPUS].[BANNERVIEWSTAT] table
----------------------------------
CREATE TABLE [CAMPUS].[BANNERVIEWSTAT] (
    CODE int NOT NULL IDENTITY (1,1),
    CALLERPAGE varchar(500) NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_CALLERPAGE DEFAULT ('') ,
    VIEWDATE date NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_VIEWDATE DEFAULT (getdate()) ,
    VIEWTIME time NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_VIEWTIME DEFAULT (CONVERT (time, GETDATE())),
    BANNER int NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_BANNER DEFAULT 1 ,
    CRTON date NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_CRTON DEFAULT (getdate()) ,
    CRTBY varchar(20) NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_CRTBY DEFAULT ('') ,
    MODON date NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_MODON DEFAULT (getdate()) ,
    MODBY varchar(20) NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_MODBY DEFAULT ('') ,
    CONSTRAINT PK_BANNERVIEWSTAT PRIMARY KEY (CODE),
    CONSTRAINT FK_BANNERVIEWSTAT_BANNER FOREIGN KEY (BANNER) REFERENCES [CAMPUS].[BANNER](CODE)
);