-- 20170330 MM c117-display-banners-record-viewcount-back-end INIT script to craete BANNERVIEWSTAT table
-- 20170331 MM c117-display-banners-record-viewcount-back-end Modified table creation to add VIEWCOUNT field and change 
--				VIEWDATE to LASTVIEWDATE and VIEWTIME to LASTVIEWTIME

-- ----------------------------
-- Drop [CAMPUS].[BANNERVIEWSTAT] table
-- ----------------------------    
IF EXISTS (
    SELECT * FROM sysobjects WHERE id = object_id(N'[CAMPUS].[BANNERVIEWSTAT]') AND OBJECTPROPERTY(id, N'IsTable') = 1
)
BEGIN
    DROP TABLE [CAMPUS].[BANNERVIEWSTAT]
END
GO

----------------------------------
-- Create [CAMPUS].[BANNERVIEWSTAT] table
----------------------------------
CREATE TABLE [CAMPUS].[BANNERVIEWSTAT] (
    CODE int NOT NULL IDENTITY (1,1),
    BANNER int NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_BANNER DEFAULT 1 ,
    VIEWCOUNT bigint NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_VIEWCOUNT DEFAULT 1 ,
    CALLERPAGE varchar(500) NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_CALLERPAGE DEFAULT ('') ,
    LASTVIEWDATE date NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_LASTVIEWDATE DEFAULT (GETDATE()) ,
    LASTVIEWTIME time NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_LASTVIEWTIME DEFAULT (CONVERT (time, GETDATE())),
    CRTON date NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_CRTON DEFAULT (GETDATE()) ,
    CRTBY varchar(20) NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_CRTBY DEFAULT ('') ,
    MODON date NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_MODON DEFAULT (GETDATE()) ,
    MODBY varchar(20) NOT NULL CONSTRAINT DF_BANNERVIEWSTAT_MODBY DEFAULT ('') ,
    CONSTRAINT PK_BANNERVIEWSTAT PRIMARY KEY (CODE),
    CONSTRAINT FK_BANNERVIEWSTAT_BANNER FOREIGN KEY (BANNER) REFERENCES [CAMPUS].[BANNER](CODE)
);