/*
* 20170421 JH c135-public-display-tutor-profile created CAM-135-select-tutor-public-data-ddl.sql and added the script to select public profile details
*/


SELECT t.*, tw.NAME AS TOWN, c.NAME AS COUNTRY, q.*, ex.*, md.* FROM [xeno-4].[CAMPUS].[TUTOR] t
INNER JOIN [CAMPUS].[TOWN] tw 
ON t.TOWN = tw.CODE
INNER JOIN [CAMPUS].[COUNTRY2] c
ON tw.COUNTRY = c.CODE
LEFT JOIN (
	SELECT tq.CODE AS QUALIFICATIONCODE, tq.NAME AS QUALIFICATION, tq.DESCRIPTION AS QDESCRIPTION, l.NAME AS QLEVEL
	FROM [CAMPUS].[TUTORQUALIFICATION] tq 
	INNER JOIN [CAMPUS].[LEVEL] l
	ON l.CODE = tq.LEVEL
	WHERE tq.ISACTIVE = 1) AS q
ON q.QUALIFICATIONCODE = t.CODE
LEFT JOIN (
	SELECT e.tutor AS TUTOREX, e.ORGANIZATION, m1.NAME AS INDUSTRY, m2.NAME AS JOBCATEGORY,
	e.COMMENCEDON, e.COMPLETIONON
	FROM [CAMPUS].[TUTORPROFESSIONALEXPERIENCE] e
	INNER JOIN [CAMPUS].[MAJOR] m1
	ON m1.CODE = e.INDUSTRY
	INNER JOIN [CAMPUS].[MAJOR] m2
	ON m2.CODE = e.JOBCATEGORY 
	WHERE e.ISACTIVE = 1) AS ex
ON ex.TUTOREX = t.CODE
LEFT JOIN (
	SELECT m.NAME AS MODULENAME, m.CODE AS MODULECODE, m.TUTOR AS MTUTOR,  p.NAME AS PROGRAMME FROM [CAMPUS].[MODULE] m
	INNER JOIN [CAMPUS].[SEMESTER] s
	ON m.SEMESTER = s.CODE
	INNER JOIN [CAMPUS].[PROGRAMME] p
	ON p.CODE = s.PROGRAMME
	WHERE m.ISTUTORRELATED = 1
	AND m.ISACTIVE = 1) AS md
ON md.MTUTOR = t.CODE
LEFT JOIN (
	SELECT cp.CODE AS CPCODE, cp.NAME AS COURSEPROVIDRE, em.TUTOR AS EMPTUTOR FROM [CAMPUS].[EMPLOYMENT] em
	INNER JOIN [CAMPUS].[COURSEPROVIDER] cp
	ON em.COURSEPROVIDER = cp.CODE 
	WHERE em.CONFIRMATIONSTATUS = 1 ) AS emp
ON t.CODE = emp.EMPTUTOR
WHERE t.CODE = 25