/*
20161222 CAM-116: PN added alter statements/create statement to add COST column into [CAMPUS].[PROGRAMME] table
*/

---------------------------------------------------------------
-----Alter Table Statements [CAMPUS].[PROGRAMME]---------
---------------------------------------------------------------

ALTER TABLE [CAMPUS].[PROGRAMME]
ADD [COST] FLOAT;

ALTER TABLE [CAMPUS].[PROGRAMME] ADD CONSTRAINT DF_PROGRAMME_COST DEFAULT(0.0) FOR COST;


------------------------
--Create [CAMPUS].[PROGRAMME ] table
------------------------
CREATE TABLE [CAMPUS].[PROGRAMME](
    CODE INT NOT NULL IDENTITY (1,1),
    NAME VARCHAR(100) NOT NULL CONSTRAINT DF_PROGRAMME_NAME DEFAULT ('') , 
    EMAIL VARCHAR(255) NOT NULL CONSTRAINT DF_PROGRAMME_EMAIL DEFAULT(''),   
    IMAGE varchar(100) NOT NULL CONSTRAINT DF_PROGRAMME_IMAGE DEFAULT (''),
    DESCRIPTION TEXT NOT NULL CONSTRAINT DF_PROGRAMME_DESCRIPTION DEFAULT (''), -- TEXT TYPE IS USED
    DURATION FLOAT NOT NULL CONSTRAINT DF_PROGRAMME_DURATION DEFAULT (0.0),
    ENTRYREQUIREMENTS VARCHAR(2000) NOT NULL CONSTRAINT DF_PROGRAMME_ENTRYREQUIREMENTS DEFAULT('NONE'),
    COUNSELORNAME VARCHAR(35) NOT NULL CONSTRAINT DF_PROGRAMME_COUNSELORNAME DEFAULT(''),
    COUNSELORPHONE VARCHAR(15) NOT NULL CONSTRAINT DF_PROGRAMME_COUNSELORPHONE DEFAULT(''),
    DISPLAYSTARTDATE DATE NOT NULL CONSTRAINT DF_PROGRAMME_DISPLAYSTARTDATE DEFAULT(GETDATE()),
    EXPIRYDATE DATE NOT NULL CONSTRAINT DF_PROGRAMME_EXPIRYDATE DEFAULT(GETDATE()),
    PROGRAMMESTATUS TINYINT NOT NULL CONSTRAINT DF_PROGRAMME_PROGRAMMESTATUS DEFAULT (''),
    COURSEPROVIDER INT NOT NULL CONSTRAINT DF_PROGRAMME_COURSEPROVIDER DEFAULT (''),
    MAJOR INT NOT NULL CONSTRAINT DF_PROGRAMME_MAJOR DEFAULT (1),
    CATEGORY INT NOT NULL CONSTRAINT DF_PROGRAMME_CATEGORY DEFAULT (1),
    LEVEL INT NOT NULL CONSTRAINT DF_PROGRAMME_LEVEL DEFAULT (1),
    CLASSTYPE INT NOT NULL CONSTRAINT DF_PROGRAMME_CLASSTYPE DEFAULT (1),
	COST FLOAT NOT NULL CONSTRAINT DF_PROGRAMME_COST DEFAULT(0.0),
    CRTON DATE NOT NULL CONSTRAINT DF_PROGRAMME_CRTON DEFAULT (getdate()) ,
    CRTBY VARCHAR(20) NOT NULL CONSTRAINT DF_PROGRAMME_CRTBY DEFAULT ('') ,
    MODON DATE NOT NULL CONSTRAINT DF_PROGRAMME_MODON DEFAULT (getdate()) ,
    MODBY VARCHAR(20) NOT NULL CONSTRAINT DF_PROGRAMME_MODBY DEFAULT ('') ,
    CONSTRAINT PK_PROGRAMME PRIMARY KEY(CODE),
    CONSTRAINT FK_PROGRAMME_COURSEPROVIDER FOREIGN KEY(COURSEPROVIDER) REFERENCES [CAMPUS].[COURSEPROVIDER],
    CONSTRAINT FK_PROGRAMME_MAJOR FOREIGN KEY(MAJOR) REFERENCES [CAMPUS].[MAJOR],
    CONSTRAINT FK_PROGRAMME_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES [CAMPUS].[CATEGORY],
    CONSTRAINT FK_PROGRAMME_CLASSTYPE FOREIGN KEY(CLASSTYPE) REFERENCES [CAMPUS].[CLASSTYPE],
    CONSTRAINT FK_PROGRAMME_LEVEL FOREIGN KEY(LEVEL) REFERENCES [CAMPUS].[LEVEL]
);
