----------------------------------------------------------------------
-- dml to create a default course provider and default user types
-- for some of the system actors
----------------------------------------------------------------------

-- -----------------------------------------------------------------
-- to create a default course provider you have to remove the foreign 
-- key constraint COURSEPROVDER_COURSEPROVIDERTOWN
-- -----------------------------------------------------------------


SET IDENTITY_INSERT [CAMPUS].[COURSEPROVIDER] ON
GO
INSERT INTO [CAMPUS].[COURSEPROVIDER] (CODE, UNIQUEPREFIX, SHORTNAME, NAME, DESCRIPTION, GENERALEMAIL, COURSEINQUIRYEMAIL, LANDPHONECOUNTRYCODE, LANDPHONEAREACODE, LANDPHONENO, LANDPHONE2NO, FAXNO, MOBILEPHONECOUNTRYCODE, MOBILEPHONENETWORKCODE, MOBILEPHONENO, SPECIALITY, WEBLINK, FACEBOOKURL, LINKEDINURL, EXPIRATIONDATE, ADDRESS1, ADDRESS2, ADDRESS3, ACCOUNTTYPE, HEADOFFICETOWN, ISTUTORRELATED, ISADMINALLOWED, COURSEPROVIDERSTATUS, COURSEPROVIDERTYPE, PRINCIPAL, TUTOR, CRTBY) 
VALUES (-1, '', '', 'Default', 'Default record for external advertisers', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, -1, 0, 0, 0, -1, NULL, NULL, 'HF');
SET IDENTITY_INSERT [CAMPUS].[COURSEPROVIDER] OFF
GO



SET IDENTITY_INSERT [CAMPUS].[USERTYPE] ON
GO
INSERT INTO [CAMPUS].[USERTYPE] (CODE, NAME, DESCRIPTION, COURSEPROVIDER, CRTBY) VALUES (-1, '', '', -1, 'HF');
SET IDENTITY_INSERT [CAMPUS].[USERTYPE] OFF
GO

SET IDENTITY_INSERT [CAMPUS].[USERTYPE] ON
GO
INSERT INTO [CAMPUS].[USERTYPE] (CODE, NAME,USERTYPESTRING, DESCRIPTION, COURSEPROVIDER, CRTBY) VALUES (1, '','FEATURED_COURSE_PROVIDER', '', -1, 'HF');
SET IDENTITY_INSERT [CAMPUS].[USERTYPE] OFF
GO


SET IDENTITY_INSERT [CAMPUS].[USERTYPE] ON
GO
INSERT INTO [CAMPUS].[USERTYPE] (CODE, NAME,USERTYPESTRING, DESCRIPTION, COURSEPROVIDER, CRTBY) VALUES (2, '','ONE_OFF_COURSE_PROVIDER', '', -1, 'HF');
SET IDENTITY_INSERT [CAMPUS].[USERTYPE] OFF
GO


SET IDENTITY_INSERT [CAMPUS].[USERTYPE] ON
GO
INSERT INTO [CAMPUS].[USERTYPE] (CODE, NAME,USERTYPESTRING, DESCRIPTION, COURSEPROVIDER, CRTBY) VALUES (3, '','STUDENT', '', -1, 'HF');
SET IDENTITY_INSERT [CAMPUS].[USERTYPE] OFF
GO

SET IDENTITY_INSERT [CAMPUS].[USERTYPE] ON
GO
INSERT INTO [CAMPUS].[USERTYPE] (CODE, NAME,USERTYPESTRING, DESCRIPTION, COURSEPROVIDER, CRTBY) VALUES (4, '','ADMIN', '', -1, 'HF');
SET IDENTITY_INSERT [CAMPUS].[USERTYPE] OFF
GO

SET IDENTITY_INSERT [CAMPUS].[USERTYPE] ON
GO
INSERT INTO [CAMPUS].[USERTYPE] (CODE, NAME,USERTYPESTRING, DESCRIPTION, COURSEPROVIDER, CRTBY) VALUES (5, '','DEO', '', -1, 'HF');
SET IDENTITY_INSERT [CAMPUS].[USERTYPE] OFF
GO





-- ----------------------------------------------------------------------------------

-- add address lines to the courseprovidertown table

-- ----------------------------------------------------------------------------------

ALTER TABLE [CAMPUS].[COURSEPROVIDERTOWN] ADD 
[ADDRESS1] [varchar](50) NULL;
ALTER TABLE [CAMPUS].[COURSEPROVIDERTOWN] ADD 
[ADDRESS2] [varchar](50) NULL;
ALTER TABLE [CAMPUS].[COURSEPROVIDERTOWN] ADD 
[ADDRESS3] [varchar](50) NULL;


ALTER TABLE [CAMPUS].[COURSEPROVIDERTOWN] ADD 
CONSTRAINT [DF_COURSEPROVIDERTOWN_ADDRESS1]  DEFAULT ('') FOR [ADDRESS1];
ALTER TABLE [CAMPUS].[COURSEPROVIDERTOWN] ADD 
CONSTRAINT [DF_COURSEPROVIDERTOWN_ADDRESS2]  DEFAULT ('') FOR [ADDRESS2];
ALTER TABLE [CAMPUS].[COURSEPROVIDERTOWN] ADD 
CONSTRAINT [DF_COURSEPROVIDERTOWN_ADDRESS3]  DEFAULT ('') FOR [ADDRESS3];